# Generated by Django 5.2.6 on 2025-09-24 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Merek')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Tahun')),
                ('color', models.CharField(max_length=50, verbose_name='Warna')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Mobil',
                'verbose_name_plural': 'Mobil',
                'ordering': ['-created_at'],
            },
        ),
    ]
