# Generated by Django 5.2.6 on 2025-09-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_cars', 'Can view all cars'), ('can_add_car', 'Can add car'), ('can_change_car', 'Can change car'), ('can_delete_car', 'Can delete car')], 'verbose_name': 'Mobil', 'verbose_name_plural': 'Mobil'},
        ),
    ]
